<?php

/**
 * @file
 *  RusaCountries.php
 *
 * @Creted 
 *  2018-03-14 - Paul Lieberman
 *
 * Countries
 */

namespace Drupal\rusa_api;

/**
 * Countries
 *
 */
class RusaCountries {

  public function getCountries() {
    $names =  [
     'Afghanistan',
     'Albania',
     'Algeria',
     'Andorra',
     'Angola',
     'Anguilla',
     'Antarctica',
     'Antigua and Barbuda',
     'Argentina',
     'Armenia',
     'Aruba',
     'Australia',
     'Austria',
     'Azerbaijan',
     'Bahamas',
     'Bahrain',
     'Bangladesh',
     'Barbados',
     'Belarus',
     'Belgium',
     'Belize',
     'Benin',
     'Bermuda',
     'Bhutan',
     'Bolivia',
     'Bonaire',
     'Bosnia and Herzegowina',
     'Botswana',
     'Brazil',
     'Brunei Darussalam',
     'Bulgaria',
     'Burkina Faso',
     'Burundi',
     'Cambodia',
     'Cameroon',
     'Canada',
     'Cape Verde',
     'Cayman Islands',
     'Central African Republic',
     'Chad',
     'Chile',
     'China',
     'Colombia',
     'Comoros',
     'Congo',
     'Cook Islands',
     'Costa Rica',
     'Cote D\'Ivoire',
     'Croatia',
     'Cuba',
     'Curacao',
     'Cyprus',
     'Czech Republic',
     'Denmark',
     'Djibouti',
     'Dominica',
     'Dominican Republic',
     'Ecuador',
     'Egypt',
     'El Salvador',
     'Equatorial Guinea',
     'Eritrea',
     'Estonia',
     'Ethiopia',
     'Falkland Islands',
     'Fiji',
     'Finland',
     'France',
     'French Guiana',
     'French Overseas Posessions',
     'Gabon',
     'Gambia',
     'Georgia',
     'Germany',
     'Ghana',
     'Gibraltar',
     'Greece',
     'Greenland',
     'Grenada',
     'Guadeloupe',
     'Guatemala',
     'Guernsey',
     'Guinea',
     'Guineabissau',
     'Guyana',
     'Haiti',
     'Honduras',
     'Hong kong',
     'Hungary',
     'Iceland',
     'India',
     'Indonesia',
     'Iran',
     'Iraq',
     'Ireland',
     'Israel',
     'Italy',
     'Jamaica',
     'Japan',
     'Jersey',
     'Jordan',
     'Kazakhstan',
     'Kenya',
     'Kiribati',
     'North Korea',
     'South Korea',
     'Kuwait',
     'Kyrgyzstan',
     'Laos',
     'Lebanon',
     'Lesotho',
     'Liberia',
     'Libyan Arab Jamahiriya',
     'Liechtenstein',
     'Luxembourg',
     'Macau',
     'Macedonia',
     'Madagascar',
     'Malawi',
     'Malaysia',
     'Maldives',
     'Mali',
     'Malta',
     'Martinique',
     'Mauritania',
     'Mauritius',
     'Mexico',
     'Moldova',
     'Monaco',
     'Mongolia',
     'Montserrat',
     'Morocco',
     'Mozambique',
     'Myanmar',
     'Namibia',
     'Nauru',
     'Nepal',
     'Netherlands',
     'New Caledonia',
     'New Zealand',
     'Nicaragua',
     'Niger',
     'Nigeria',
     'Niue',
     'Norway',
     'Oman',
     'Pacific Islands of Micronesia',
     'Pakistan',
     'Panama',
     'Papua New Guinea',
     'Paraguay',
     'Peru',
     'Philippines',
     'Poland',
     'Portugal',
     'Qatar',
     'Reunion',
     'Romania',
     'Russia',
     'Rwanda',
     'Saba',
     'Saint Kitts and Nevis',
     'Saint Lucia',
     'Saint Vincent and the Grenadines',
     'Samoa',
     'San Marino',
     'Sao Tome and Principe',
     'Saudi Arabia',
     'Senegal',
     'Seychelles',
     'Sierra Leone',
     'Singapore',
     'Slovakia',
     'Slovenia',
     'Solomon Islands',
     'Somalia',
     'South Africa',
     'Spain',
     'Sri Lanka',
     'St Eustatius',
     'St Maarten',
     'Sudan',
     'Suriname',
     'Swaziland',
     'Sweden',
     'Switzerland',
     'Syrian Arab Republic',
     'Tahiti',
     'Taiwan',
     'Tajikistan',
     'Tanzania',
     'Thailand',
     'Togo',
     'Tonga',
     'Trinidad and Tobago',
     'Tunisia',
     'Turkey',
     'Turkmenistan',
     'Turks and Caicos Islands',
     'Tuvalu',
     'Uganda',
     'Ukraine',
     'United Arab Emirates',
     'United Kingdom',
     'United States',
     'Uruguay',
     'Uzbekistan',
     'Vanuatu',
     'Vatican City',
     'Venezuela',
     'Vietnam',
     'Virgin Islands UK',
     'Yemen',
     'Yugoslavia',
     'Zaire',
     'Zambia',
     'Zimbabwe',
    ];
    $countries = [];
    foreach ($names as $name) {
      $countries[$name] = $name;
    }
    return $countries;
  }
}
